set_frequency:
  name: "Set Frequency"
  description: "Set the frequency of the device."
  fields:
    frequency:
      name: "Frequency"
      description: "The frequency to set."
    device_id:
      name: "Device ID"
      description: "The ID of the device to set the frequency for."
