set_frequency:
  description: "Set the data fetch frequency for a specific device."
  fields:
    frequency:
      description: "The new frequency in seconds for data fetching."
      example: 10
    device_id:
      description: "The ID of the device to update the frequency for."
      example: "192.168.3.143"
